export const LOGIN_REDUCER = {
  SET_EMAIL: 'SET_EMAIL',
  SET_PASSWORD: 'SET_PASSWORD',
  SET_EMAIL_ERROR: 'SET_EMAIL_ERROR',
  SET_PASSWORD_ERROR: 'SET_PASSWORD_ERROR',
  SET_USER_DETAILS: 'SET_USER_DETAILS'
}

export const PROJECTS_REDUCER = {
  SET_PROJECT_LIST: 'SET_PROJECT_LIST'
}